"""Helpers for exposing ingestion safely through admin APIs."""

from __future__ import annotations

import re
import sys
import uuid
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import tomllib
except ImportError:  # pragma: no cover - Python 3.12 has tomllib
    import tomli as tomllib  # type: ignore

from fastapi import HTTPException, UploadFile, status

_BACKEND_DIR = Path(__file__).resolve().parents[2]
_REPO_ROOT = _BACKEND_DIR if (_BACKEND_DIR / "pipelines").exists() else _BACKEND_DIR.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

APP_DATA_DIR = _REPO_ROOT / "data"
APPROVED_CONFIG_DIR = _REPO_ROOT / "pipelines" / "configs"
INGESTION_DEFAULTS_PATH = APPROVED_CONFIG_DIR / "admin_ingestion_defaults.toml"
UPLOAD_ROOT = APP_DATA_DIR / "admin_uploads" / "pdf"
JOB_WORK_ROOT = APP_DATA_DIR / "ingestion_jobs"
WORKER_HEARTBEAT_PATH = JOB_WORK_ROOT / "worker_heartbeat.json"
ALLOWED_CACHE_ROOT = APP_DATA_DIR / "corpora"

SAFE_PATH_PART = re.compile(r"[^A-Za-z0-9._ -]+")
SAFE_CONFIG_NAME = re.compile(r"^[A-Za-z0-9._ -]+\.toml$")
SUPPORTED_SOURCES = {
    "pubmed_abstract",
    "pmc_fulltext",
    "pdf",
    "lab_protocols",
    "eln_lims",
    "inventories",
    "omics_summaries",
}
LOCAL_TEXT_SOURCES = {"lab_protocols"}
LOCAL_TABLE_SOURCES = {"eln_lims", "inventories", "omics_summaries"}
EMBEDDING_MODELS = {"pubmedbert", "minilm"}


def load_toml(path: Path) -> dict[str, Any]:
    with open(path, "rb") as handle:
        return tomllib.load(handle)


def format_toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(format_toml_value(item) for item in value) + "]"
    if value is None:
        return '""'
    return json.dumps(str(value))


def dump_toml_sections(config: dict[str, Any]) -> str:
    ordered_sections = [
        "corpus",
        "pubmed",
        "pmc",
        "pdf",
        "lab_protocols",
        "eln_lims",
        "inventories",
        "omics_summaries",
        "local",
        "chunking",
        "indexing",
    ]
    section_names = [section for section in ordered_sections if section in config]
    section_names.extend(sorted(section for section in config if section not in section_names))

    lines: list[str] = ["# RLALab corpus configuration", "# Generated by the admin ingestion config editor.", ""]
    for section_name in section_names:
        section = config.get(section_name)
        if not isinstance(section, dict):
            continue
        lines.append(f"[{section_name}]")
        for key, value in section.items():
            lines.append(f"{key} = {format_toml_value(value)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def write_worker_heartbeat(*, state: str, job_id: uuid.UUID | None = None) -> None:
    WORKER_HEARTBEAT_PATH.parent.mkdir(parents=True, exist_ok=True)
    WORKER_HEARTBEAT_PATH.write_text(
        json.dumps(
            {
                "state": state,
                "job_id": str(job_id) if job_id else None,
                "updated_at": utcnow().isoformat(),
            },
            sort_keys=True,
        )
        + "\n"
    )


def get_worker_status(stale_after_seconds: int = 120) -> dict[str, Any]:
    if not WORKER_HEARTBEAT_PATH.exists():
        return {
            "active": False,
            "state": "not_seen",
            "job_id": None,
            "updated_at": None,
            "seconds_since_heartbeat": None,
            "message": "No ingestion worker heartbeat has been seen.",
        }

    try:
        payload = json.loads(WORKER_HEARTBEAT_PATH.read_text())
        updated_at = datetime.fromisoformat(str(payload["updated_at"]))
        if updated_at.tzinfo is None:
            updated_at = updated_at.replace(tzinfo=timezone.utc)
    except Exception:
        return {
            "active": False,
            "state": "invalid",
            "job_id": None,
            "updated_at": None,
            "seconds_since_heartbeat": None,
            "message": "The ingestion worker heartbeat file is unreadable.",
        }

    age = (utcnow() - updated_at.astimezone(timezone.utc)).total_seconds()
    active = age <= stale_after_seconds
    return {
        "active": active,
        "state": payload.get("state") or "unknown",
        "job_id": payload.get("job_id"),
        "updated_at": updated_at.isoformat(),
        "seconds_since_heartbeat": int(age),
        "message": "Worker heartbeat is current." if active else "Ingestion worker heartbeat is stale.",
    }


def list_approved_configs() -> list[dict[str, Any]]:
    configs: list[dict[str, Any]] = []
    if not APPROVED_CONFIG_DIR.is_dir():
        return configs

    for path in sorted(APPROVED_CONFIG_DIR.glob("*.toml")):
        if path.name == INGESTION_DEFAULTS_PATH.name:
            continue
        cfg = load_toml(path)
        corpus = cfg.get("corpus", {})
        pubmed = cfg.get("pubmed", {})
        pdf = cfg.get("pdf", {})
        source = str(corpus.get("source", ""))
        configs.append(
            {
                "name": path.name,
                "path": str(path),
                "corpus_name": corpus.get("name", path.stem),
                "source": source,
                "embedding_model": corpus.get("embedding_model", "pubmedbert"),
                "year_from": pubmed.get("year_from"),
                "year_to": pubmed.get("year_to"),
                "pdf_dir": pdf.get("dir"),
                "supports_pdf_upload": source == "pdf",
            }
        )
    return configs


def validate_config_name(config_name: str, *, must_exist: bool) -> Path:
    requested = Path(config_name).name
    if requested != config_name or not SAFE_CONFIG_NAME.fullmatch(requested):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Config name must be a plain .toml filename",
        )
    if requested == INGESTION_DEFAULTS_PATH.name:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="The admin defaults config cannot be edited here",
        )
    config_path = (APPROVED_CONFIG_DIR / requested).resolve()
    config_dir = APPROVED_CONFIG_DIR.resolve()
    if config_path.parent != config_dir:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Config path must stay under pipelines/configs",
        )
    if must_exist and not config_path.is_file():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Ingestion config not found")
    if not must_exist and config_path.exists():
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Ingestion config already exists")
    return config_path


def get_ingestion_config_detail(config_name: str) -> dict[str, Any]:
    config_path = validate_config_name(Path(config_name).name, must_exist=True)
    return {
        "name": config_path.name,
        "path": str(config_path),
        "content": load_toml(config_path),
    }


def _section(config: dict[str, Any], name: str) -> dict[str, Any]:
    value = config.get(name)
    if value is None:
        value = {}
        config[name] = value
    if not isinstance(value, dict):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"[{name}] must be a TOML table")
    return value


def _required_string(section: dict[str, Any], key: str, label: str) -> None:
    value = section.get(key)
    if not isinstance(value, str) or not value.strip():
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"{label} is required")
    section[key] = value.strip()


def _optional_string(section: dict[str, Any], key: str) -> None:
    value = section.get(key)
    if value is None or value == "":
        section.pop(key, None)
        return
    if not isinstance(value, str):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"{key} must be text")
    section[key] = value.strip()


def _int_field(section: dict[str, Any], key: str, label: str, *, required: bool = True) -> None:
    value = section.get(key)
    if (value is None or value == "") and not required:
        section.pop(key, None)
        return
    if isinstance(value, bool) or not isinstance(value, int):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"{label} must be an integer")


def _positive_number(section: dict[str, Any], key: str, label: str, *, required: bool = True) -> None:
    value = section.get(key)
    if (value is None or value == "") and not required:
        section.pop(key, None)
        return
    if isinstance(value, bool) or not isinstance(value, (int, float)) or value <= 0:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"{label} must be positive")


def _bool_field(section: dict[str, Any], key: str) -> None:
    value = section.get(key)
    if value is None or value == "":
        section.pop(key, None)
        return
    if not isinstance(value, bool):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"{key} must be true or false")


def validate_ingestion_config_content(content: dict[str, Any]) -> dict[str, Any]:
    config = {key: dict(value) if isinstance(value, dict) else value for key, value in content.items()}
    corpus = _section(config, "corpus")
    _required_string(corpus, "name", "Corpus name")
    _required_string(corpus, "source", "Corpus source")
    source = corpus["source"]
    if source not in SUPPORTED_SOURCES:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Unsupported corpus source")
    embedding_model = str(corpus.get("embedding_model") or "pubmedbert").strip()
    if embedding_model not in EMBEDDING_MODELS:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Unsupported embedding model")
    corpus["embedding_model"] = embedding_model

    if source == "pubmed_abstract":
        pubmed = _section(config, "pubmed")
        _required_string(pubmed, "query", "PubMed query")
        _int_field(pubmed, "year_from", "Year from")
        _int_field(pubmed, "year_to", "Year to")
        if pubmed["year_from"] > pubmed["year_to"]:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Year from cannot exceed year to")
        _int_field(pubmed, "batch_size", "Batch size")
        if pubmed["batch_size"] <= 0:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Batch size must be positive")
        _positive_number(pubmed, "sleep_between_batches_s", "Sleep between batches")

    if source == "pmc_fulltext":
        pmc = _section(config, "pmc")
        ids = pmc.get("ids")
        if ids is None or ids == "":
            pmc.pop("ids", None)
        elif not isinstance(ids, list) or not all(isinstance(item, str) and item.strip() for item in ids):
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="PMC IDs must be a list of text IDs")
        _optional_string(pmc, "pmc_id_file")
        _bool_field(pmc, "from_cached_pubmed_documents")
        _positive_number(pmc, "sleep_between_batches_s", "Sleep between batches")
        if not pmc.get("ids") and not pmc.get("pmc_id_file") and not pmc.get("from_cached_pubmed_documents"):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="PMC config needs IDs, a PMCID file, or cached PubMed documents",
            )

    if source == "pdf":
        pdf = _section(config, "pdf")
        _required_string(pdf, "dir", "PDF directory")

    if source in LOCAL_TEXT_SOURCES | LOCAL_TABLE_SOURCES:
        local = _section(config, source)
        _required_string(local, "dir", "Local source directory")
        for key in ("access_status", "sensitivity", "owner", "retention_policy"):
            _optional_string(local, key)
        if source in LOCAL_TABLE_SOURCES:
            _int_field(local, "max_rows", "Max rows", required=False)
            if "max_rows" in local and local["max_rows"] <= 0:
                raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Max rows must be positive")

    if "chunking" in config:
        chunking = _section(config, "chunking")
        _int_field(chunking, "chunk_size", "Chunk size", required=False)
        _int_field(chunking, "chunk_overlap", "Chunk overlap", required=False)
        if "chunk_size" in chunking and chunking["chunk_size"] <= 0:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Chunk size must be positive")
        if "chunk_overlap" in chunking and chunking["chunk_overlap"] < 0:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Chunk overlap cannot be negative")

    if "indexing" in config:
        indexing = _section(config, "indexing")
        _int_field(indexing, "embedding_batch_size", "Embedding batch size", required=False)
        if "embedding_batch_size" in indexing and indexing["embedding_batch_size"] <= 0:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Embedding batch size must be positive")

    return config


def save_ingestion_config(config_name: str, content: dict[str, Any], *, create: bool) -> dict[str, Any]:
    config_path = validate_config_name(config_name, must_exist=not create)
    validated = validate_ingestion_config_content(content)
    APPROVED_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    config_path.write_text(dump_toml_sections(validated), encoding="utf-8")
    return {
        "name": config_path.name,
        "path": str(config_path),
        "content": validated,
    }


def load_ingestion_defaults() -> dict[str, Any]:
    defaults = {
        "config_name": "",
        "mode": "full",
        "cache_path": "",
        "write_acquisition_queue": False,
        "include_cached_fulltext": False,
    }
    if INGESTION_DEFAULTS_PATH.is_file():
        raw = load_toml(INGESTION_DEFAULTS_PATH).get("defaults", {})
        defaults.update({key: value for key, value in raw.items() if key in defaults})

    config_name = str(defaults.get("config_name") or "")
    if config_name:
        try:
            get_approved_config(config_name)
        except HTTPException:
            defaults["config_name"] = ""

    mode = str(defaults.get("mode") or "full")
    if mode not in {"full", "incremental", "test_year", "local_only", "queue_only"}:
        defaults["mode"] = "full"

    cache_path = str(defaults.get("cache_path") or "")
    if cache_path:
        validate_cache_path(cache_path)

    return defaults


def get_approved_config(config_name: str) -> tuple[Path, dict[str, Any]]:
    requested = Path(config_name).name
    config_path = (APPROVED_CONFIG_DIR / requested).resolve()
    config_dir = APPROVED_CONFIG_DIR.resolve()
    if config_path.parent != config_dir or not config_path.is_file() or config_path.suffix != ".toml":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Unknown ingestion config",
        )
    return config_path, load_toml(config_path)


def validate_cache_path(cache_path: str | None) -> str | None:
    if not cache_path:
        return None
    path = Path(cache_path).expanduser()
    if not path.is_absolute():
        path = _REPO_ROOT / path
    resolved = path.resolve()
    allowed_root = ALLOWED_CACHE_ROOT.resolve()
    if resolved != allowed_root and allowed_root not in resolved.parents:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Cache path must live under data/corpora",
        )
    return str(resolved)


def read_cache_document_error_reports(cache_paths: list[str]) -> list[dict[str, Any]]:
    reports: list[dict[str, Any]] = []
    seen: set[str] = set()
    for raw_cache_path in cache_paths:
        cache_path = validate_cache_path(raw_cache_path)
        if cache_path is None or cache_path in seen:
            continue
        seen.add(cache_path)

        cache_root = Path(cache_path)
        candidates = [
            cache_root / "normalized" / "documents.errors.jsonl",
            cache_root / "normalized" / "documents.error.jsonl",
        ]
        error_path = next((path for path in candidates if path.is_file()), candidates[0])
        records: list[dict[str, Any]] = []
        parse_errors: list[str] = []

        if error_path.is_file():
            for index, line in enumerate(error_path.read_text(encoding="utf-8").splitlines(), start=1):
                if not line.strip():
                    continue
                try:
                    parsed = json.loads(line)
                    records.append(parsed if isinstance(parsed, dict) else {"value": parsed})
                except json.JSONDecodeError as exc:
                    parse_errors.append(f"Line {index}: {exc.msg}")
                    records.append({"line": index, "raw": line})

        reports.append(
            {
                "cache_path": cache_path,
                "error_file_path": str(error_path),
                "exists": error_path.is_file(),
                "record_count": len(records),
                "records": records,
                "parse_errors": parse_errors,
            }
        )
    return reports


def read_cache_acquisition_queue_reports(cache_paths: list[str]) -> list[dict[str, Any]]:
    reports: list[dict[str, Any]] = []
    seen: set[str] = set()
    for raw_cache_path in cache_paths:
        cache_path = validate_cache_path(raw_cache_path)
        if cache_path is None or cache_path in seen:
            continue
        seen.add(cache_path)

        queue_path = Path(cache_path) / "reports" / "acquisition_queue.jsonl"
        records: list[dict[str, Any]] = []
        parse_errors: list[str] = []

        if queue_path.is_file():
            for index, line in enumerate(queue_path.read_text(encoding="utf-8").splitlines(), start=1):
                if not line.strip():
                    continue
                try:
                    parsed = json.loads(line)
                    records.append(parsed if isinstance(parsed, dict) else {"value": parsed})
                except json.JSONDecodeError as exc:
                    parse_errors.append(f"Line {index}: {exc.msg}")
                    records.append({"line": index, "raw": line})

        reports.append(
            {
                "cache_path": cache_path,
                "queue_file_path": str(queue_path),
                "exists": queue_path.is_file(),
                "record_count": len(records),
                "records": records,
                "parse_errors": parse_errors,
            }
        )
    return reports


def safe_pdf_relative_path(filename: str) -> Path:
    parts = [part for part in filename.replace("\\", "/").split("/") if part not in {"", ".", ".."}]
    if not parts:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Uploaded file has no name")
    safe_parts = [SAFE_PATH_PART.sub("_", part).strip() for part in parts]
    safe_parts = [part or "unnamed" for part in safe_parts]
    path = Path(*safe_parts)
    if path.suffix.lower() != ".pdf":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only PDF files can be uploaded for folder ingestion",
        )
    return path


async def save_pdf_upload_folder(files: list[UploadFile], *, batch_id: uuid.UUID) -> tuple[Path, int, int]:
    if not files:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Upload at least one PDF file",
        )

    destination_root = UPLOAD_ROOT / str(batch_id)
    destination_root.mkdir(parents=True, exist_ok=True)
    total_bytes = 0
    file_count = 0
    used_paths: set[Path] = set()

    for upload in files:
        relative_path = safe_pdf_relative_path(upload.filename or "document.pdf")
        destination = destination_root / relative_path
        if relative_path in used_paths or destination.exists():
            destination = destination.with_name(f"{destination.stem}-{file_count + 1}{destination.suffix}")
        used_paths.add(destination.relative_to(destination_root))
        destination.parent.mkdir(parents=True, exist_ok=True)

        written = 0
        with open(destination, "wb") as handle:
            while chunk := await upload.read(1024 * 1024):
                written += len(chunk)
                handle.write(chunk)
        if written == 0:
            destination.unlink(missing_ok=True)
            continue
        total_bytes += written
        file_count += 1

    if file_count == 0:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No non-empty PDF files were uploaded",
        )
    return destination_root, file_count, total_bytes
