"""Datasheet feature round 1: templates, runs, candidates, metadata sidecar

Adds the four round-1 datasheet tables and the document metadata sidecar columns.
The extraction tables (datasheet_rows, datasheet_numeric_claims, datasheet_gold_*)
land in round 2 — see docs/DATASHEET_FEATURE_PLAN.md §4.1.

Hand-written rather than autogenerated: alembic autogenerate does not reliably
detect ARRAY column additions, and this revision also creates a GIN index.

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-29
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID


revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── Metadata sidecar on documents ────────────────────────────────────────
    op.add_column("documents", sa.Column("taxids", ARRAY(sa.Integer())))
    op.add_column("documents", sa.Column("product_classes", ARRAY(sa.String())))
    op.add_column("documents", sa.Column("publisher", sa.String()))
    op.add_column("documents", sa.Column("oa_status", sa.String()))
    op.add_column("documents", sa.Column("doc_type", sa.String()))
    op.add_column(
        "documents",
        sa.Column("is_review", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column(
        "documents",
        sa.Column("is_retracted", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("documents", sa.Column("retraction_checked_at", sa.DateTime(timezone=True)))
    op.add_column("documents", sa.Column("preprint_of_doi", sa.String()))
    op.add_column("documents", sa.Column("full_text_source", sa.String()))
    op.add_column("documents", sa.Column("access_route", sa.String()))
    op.add_column(
        "documents",
        sa.Column("chat_visible", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )
    op.create_index(
        "idx_documents_taxids", "documents", ["taxids"], postgresql_using="gin"
    )
    op.create_index("idx_documents_doc_type", "documents", ["doc_type"])
    # Partial index: chat retrieval always filters on these two, and the vast
    # majority of rows are visible + not retracted.
    op.create_index(
        "idx_documents_chat_visible",
        "documents",
        ["chat_visible"],
        postgresql_where=sa.text("chat_visible IS TRUE AND is_retracted IS FALSE"),
    )

    op.add_column("document_chunks", sa.Column("section_label", sa.String()))
    op.create_index("idx_chunks_section", "document_chunks", ["section_label"])

    # ── datasheet_templates ──────────────────────────────────────────────────
    op.create_table(
        "datasheet_templates",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("description", sa.Text()),
        sa.Column("is_default", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("created_by_user_id", UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
        sa.Column("metadata", JSONB),
    )
    op.create_index("ix_datasheet_templates_name", "datasheet_templates", ["name"], unique=True)

    # ── datasheet_template_columns ───────────────────────────────────────────
    op.create_table(
        "datasheet_template_columns",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "template_id",
            UUID(as_uuid=True),
            sa.ForeignKey("datasheet_templates.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("vocabulary", JSONB),
        sa.Column("extraction_hint", sa.Text()),
        sa.Column("source_hint", sa.String(), nullable=False, server_default="any"),
        sa.Column("required", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.UniqueConstraint("template_id", "key", name="uq_datasheet_template_columns_key"),
        sa.UniqueConstraint("template_id", "order_index", name="uq_datasheet_template_columns_order"),
    )
    op.create_index(
        "ix_datasheet_template_columns_template_id",
        "datasheet_template_columns",
        ["template_id"],
    )

    # ── datasheet_runs ───────────────────────────────────────────────────────
    op.create_table(
        "datasheet_runs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("requested_by_user_id", UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL")),
        sa.Column("status", sa.String(), nullable=False, server_default="queued"),
        sa.Column("phase", sa.String()),
        sa.Column("stop_after_phase", sa.String(), nullable=False, server_default="export"),
        sa.Column("seed_kind", sa.String(), nullable=False),
        sa.Column("organism_name", sa.String()),
        sa.Column("organism_taxid", sa.Integer()),
        sa.Column("organism_synonyms", JSONB),
        sa.Column("product_term", sa.String()),
        sa.Column("product_ids", JSONB),
        sa.Column("product_synonyms", JSONB),
        sa.Column("product_classes", ARRAY(sa.String())),
        sa.Column("year_from", sa.Integer()),
        sa.Column("year_to", sa.Integer()),
        sa.Column("template_id", UUID(as_uuid=True), sa.ForeignKey("datasheet_templates.id", ondelete="SET NULL")),
        sa.Column("template_snapshot", JSONB, nullable=False),
        sa.Column("config_snapshot", JSONB),
        sa.Column("cache_path", sa.Text()),
        sa.Column("manifest_id", UUID(as_uuid=True), sa.ForeignKey("ingestion_manifests.id", ondelete="SET NULL")),
        sa.Column("csv_path", sa.Text()),
        sa.Column("candidate_count", sa.Integer()),
        sa.Column("acquired_count", sa.Integer()),
        sa.Column("ingested_count", sa.Integer()),
        sa.Column("extracted_count", sa.Integer()),
        sa.Column("prompt_tokens", sa.Integer()),
        sa.Column("completion_tokens", sa.Integer()),
        sa.Column("cached_tokens", sa.Integer()),
        sa.Column("progress_message", sa.Text()),
        sa.Column("log_tail", sa.Text()),
        sa.Column("error", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    )
    op.create_index("ix_datasheet_runs_status", "datasheet_runs", ["status"])

    # ── datasheet_candidates ─────────────────────────────────────────────────
    op.create_table(
        "datasheet_candidates",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "run_id",
            UUID(as_uuid=True),
            sa.ForeignKey("datasheet_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("doi", sa.String()),
        sa.Column("pmid", sa.String()),
        sa.Column("pmc_id", sa.String()),
        sa.Column("title", sa.Text()),
        sa.Column("journal", sa.String()),
        sa.Column("publisher", sa.String()),
        sa.Column("year", sa.Integer()),
        sa.Column("found_in", ARRAY(sa.String())),
        sa.Column("oa_status", sa.String()),
        sa.Column("license", sa.String()),
        sa.Column("is_preprint", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("version_of_record_doi", sa.String()),
        sa.Column("doc_type", sa.String()),
        sa.Column("is_review", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("is_retracted", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("retraction_checked_at", sa.DateTime(timezone=True)),
        sa.Column("relevance", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("relevance_reason", sa.Text()),
        sa.Column("acquisition_route", sa.String()),
        sa.Column("acquisition_status", sa.String(), nullable=False, server_default="pending"),
        sa.Column("resolver_url", sa.Text()),
        sa.Column("asset_path", sa.Text()),
        sa.Column("document_id", UUID(as_uuid=True), sa.ForeignKey("documents.id", ondelete="SET NULL")),
        sa.Column("dedupe_group", sa.String()),
        sa.Column("notes", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    )
    op.create_index("ix_datasheet_candidates_run_id", "datasheet_candidates", ["run_id"])
    op.create_index(
        "ix_datasheet_candidates_acquisition_status",
        "datasheet_candidates",
        ["acquisition_status"],
    )
    # One row per (run, DOI). Papers without a DOI are deduped on title later and
    # are deliberately not constrained here.
    op.create_index(
        "idx_datasheet_candidates_run_doi",
        "datasheet_candidates",
        ["run_id", "doi"],
        unique=True,
        postgresql_where=sa.text("doi IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index("idx_datasheet_candidates_run_doi", table_name="datasheet_candidates")
    op.drop_index("ix_datasheet_candidates_acquisition_status", table_name="datasheet_candidates")
    op.drop_index("ix_datasheet_candidates_run_id", table_name="datasheet_candidates")
    op.drop_table("datasheet_candidates")

    op.drop_index("ix_datasheet_runs_status", table_name="datasheet_runs")
    op.drop_table("datasheet_runs")

    op.drop_index(
        "ix_datasheet_template_columns_template_id", table_name="datasheet_template_columns"
    )
    op.drop_table("datasheet_template_columns")

    op.drop_index("ix_datasheet_templates_name", table_name="datasheet_templates")
    op.drop_table("datasheet_templates")

    op.drop_index("idx_chunks_section", table_name="document_chunks")
    op.drop_column("document_chunks", "section_label")

    op.drop_index("idx_documents_chat_visible", table_name="documents")
    op.drop_index("idx_documents_doc_type", table_name="documents")
    op.drop_index("idx_documents_taxids", table_name="documents")
    for column in (
        "chat_visible",
        "access_route",
        "full_text_source",
        "preprint_of_doi",
        "retraction_checked_at",
        "is_retracted",
        "is_review",
        "doc_type",
        "oa_status",
        "publisher",
        "product_classes",
        "taxids",
    ):
        op.drop_column("documents", column)
