"""Datasheet round 2: extracted rows, numeric claims, gold set, gold scores.

Round 1 deliberately shipped four tables and no more — there was no point creating
tables nothing wrote to. These four are what the extraction pass needs:

- `datasheet_rows`      one row per paper, cells carrying value + provenance
- `datasheet_numeric_claims`  parsed quantities, because vector search cannot rank
                        numbers (D11)
- `datasheet_gold_rows` the curated spreadsheet, imported for scoring (D7)
- `datasheet_gold_scores`  per-column accuracy per run, per scoring method

Hand-written rather than autogenerated: alembic does not detect ARRAY or vector
column changes reliably, and this migration is checked against the ORM by
`tests/test_migration_matches_orm.py` rather than by trusting autogenerate.

Revision ID: 0010
Revises: 0009
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "datasheet_rows",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "run_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("datasheet_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "candidate_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("datasheet_candidates.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "document_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("documents.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("cells", postgresql.JSONB(), nullable=False),
        sa.Column("source_tier", sa.String(), nullable=False),
        sa.Column("extraction_model", sa.String(), nullable=True),
        sa.Column("template_version", sa.Integer(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "review_status", sa.String(), nullable=False, server_default=sa.text("'unreviewed'")
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("run_id", "candidate_id", name="uq_datasheet_rows_run_candidate"),
    )
    op.create_index("ix_datasheet_rows_run_id", "datasheet_rows", ["run_id"])

    op.create_table(
        "datasheet_numeric_claims",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "row_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("datasheet_rows.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("compound", sa.String(), nullable=True),
        sa.Column("compound_normalized", sa.String(), nullable=True),
        sa.Column("value_min", sa.Float(), nullable=True),
        sa.Column("value_max", sa.Float(), nullable=True),
        sa.Column("unit_raw", sa.String(), nullable=True),
        sa.Column("unit_canonical", sa.String(), nullable=True),
        sa.Column("basis", sa.String(), nullable=True),
        # NULL whenever the bases are not comparable. Do not backfill it with a
        # converted figure: a g/L and a mg/g value measure different things.
        sa.Column("value_si", sa.Float(), nullable=True),
        sa.Column("comparable", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("qualifier", sa.String(), nullable=True),
        sa.Column("cultivation_mode", sa.String(), nullable=True),
        sa.Column("scale", sa.String(), nullable=True),
        sa.Column("evidence_quote", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_datasheet_numeric_claims_row_id", "datasheet_numeric_claims", ["row_id"])
    op.create_index(
        "ix_datasheet_numeric_claims_compound_normalized",
        "datasheet_numeric_claims",
        ["compound_normalized"],
    )

    op.create_table(
        "datasheet_gold_rows",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "template_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("datasheet_templates.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("pmid", sa.String(), nullable=True),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column("cells", postgresql.JSONB(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("source", "link", name="uq_datasheet_gold_rows_source_link"),
    )
    op.create_index("ix_datasheet_gold_rows_doi", "datasheet_gold_rows", ["doi"])

    op.create_table(
        "datasheet_gold_scores",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "run_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("datasheet_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("column_key", sa.String(), nullable=False),
        sa.Column("matched", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("partial", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("missed", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("not_in_gold", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("detail", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("run_id", "column_key", "method", name="uq_datasheet_gold_scores_key"),
    )
    op.create_index("ix_datasheet_gold_scores_run_id", "datasheet_gold_scores", ["run_id"])


def downgrade() -> None:
    op.drop_table("datasheet_gold_scores")
    op.drop_table("datasheet_gold_rows")
    op.drop_table("datasheet_numeric_claims")
    op.drop_table("datasheet_rows")
